// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBaAZ_q3caakcMjnvMbp-xlQYE9j2ZnE8',
    appId: '1:1070193541110:web:b3c9b5b49144fa9fad51d7',
    messagingSenderId: '1070193541110',
    projectId: 'dailydo-87848',
    authDomain: 'dailydo-87848.firebaseapp.com',
    storageBucket: 'dailydo-87848.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFisC4VQD9u1N_K_Kj78qypS6nELDqk6U',
    appId: '1:1070193541110:android:b706814692d92845ad51d7',
    messagingSenderId: '1070193541110',
    projectId: 'dailydo-87848',
    storageBucket: 'dailydo-87848.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHgBUMmKS5T7z40o-nlUpmgl5beO0-ClQ',
    appId: '1:1070193541110:ios:9342a45e1ad969c6ad51d7',
    messagingSenderId: '1070193541110',
    projectId: 'dailydo-87848',
    storageBucket: 'dailydo-87848.appspot.com',
    iosBundleId: 'com.example.dailyDoii',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHgBUMmKS5T7z40o-nlUpmgl5beO0-ClQ',
    appId: '1:1070193541110:ios:40b4acd2bdb5ddb7ad51d7',
    messagingSenderId: '1070193541110',
    projectId: 'dailydo-87848',
    storageBucket: 'dailydo-87848.appspot.com',
    iosBundleId: 'com.example.dailyDoii.RunnerTests',
  );
}
